=== Jniecor/LMSGI_UD4/Librería/ListaLibros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Autores" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Autor" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Apellido1" type="xs:string"/>
                                                    <xs:element name="Apellido2" type="xs:string"/>
                                                    <xs:element name="Nombre" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Título"/>
                            <xs:element name="ISBN"/>
                            <xs:element name="Editorial"/>
                            <xs:element name="Fecha_de_publicación"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jniecor/LMSGI_UD4/Librería/ListaLibros_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ListaLibros.xsd">
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y la piedra filosofal</Título>
        <ISBN>8478884459</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>26 de junio de 2000</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y la cámara secreta</Título>
        <ISBN>8478884955</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>26 de junio del 2000</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y el prisionero de Azkabán</Título>
        <ISBN>847888615X</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>26 de junio del 2001</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y el Caliz de Fuego</Título>
        <ISBN>8478886451</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>4 de marzo de 2002</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y la Orden del Fénix</Título>
        <ISBN>8478887423</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>26 de junio de 2004</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y la piedra filosofal</Título>
        <ISBN>8478884459</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>26 de junio de 2000</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y la cámara secreta</Título>
        <ISBN>8478884955</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>26 de junio del 2000</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y el prisionero de Azkabán</Título>
        <ISBN>847888615X</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>26 de junio del 2001</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y el Caliz de Fuego</Título>
        <ISBN>8478886451</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>4 de marzo de 2002</Fecha_de_publicación>
    </Libro>
    <Libro>
        <Autores>
            <Autor>
                <Apellido1>Kathleen</Apellido1>
                <Apellido2>Rowling</Apellido2>
                <Nombre>Joanne</Nombre>
            </Autor>      
        </Autores>
        <Título>Harry Potter y la Orden del Fénix</Título>
        <ISBN>8478887423</ISBN>
        <Editorial>Salamandra</Editorial>
        <Fecha_de_publicación>26 de junio de 2004</Fecha_de_publicación>
    </Libro>
</Libros>
