=== Jniecor/LMSGI_UD4/Prácticas CFGS/Practicas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation xml:lang="Es-es">
      Esquema de las prácticas CFGS
      <fecha>04/02/2022</fecha>
      <autor>Julio Nieto Cordón</autor>
    </xs:documentation>
  </xs:annotation>
  <xs:element name="Practicas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Alumnos">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Alumno">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="NIF" type="xs:string" />
                    <xs:element name="Resultado" type="xs:string" />
                    <xs:element name="Observaciones" type="xs:string" />
                    <xs:element name="IP" />
                  </xs:sequence>
                  <xs:attribute name="nombre" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jniecor/LMSGI_UD4/Prácticas CFGS/PracticasCFGS_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Practicas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Practicas.xsd">
    <Alumnos>
        <Alumno nombre="José Luis Altozano">
            <NIF>58741536H</NIF>
            <Resultado>APTO</Resultado>
            <Observaciones>Cumple con los requisitos</Observaciones>
            <IP></IP>
        </Alumno>
        <Alumno nombre="Francisco Guerra">
            <NIF>58245784K</NIF>
            <Resultado>APTO</Resultado>
            <Observaciones>Ejercicio completo</Observaciones>
            <IP></IP>
        </Alumno>
        <Alumno nombre="José Canto">
            <NIF>86953114G</NIF>
            <Resultado>NO APTO</Resultado>
            <Observaciones>El esfuerzo ha sido nulo</Observaciones>
            <IP></IP>
        </Alumno>
        <Alumno nombre="Antonio de Guadalupe">
            <NIF>59631578D</NIF>
            <Resultado>APTO</Resultado>
            <Observaciones>Cumple con los requisitos</Observaciones>
            <IP></IP>
        </Alumno>
    </Alumnos>
</Practicas>
