=== Jniecor/LMSGI_UD4/Clientes/sede.dtd
<!ELEMENT Sedes (sede*)>
<!ELEMENT sede (codsede, nomempleado, fechaAlta, descripcioncliente, clientes)>
<!ELEMENT clientes (codcliente, numviviendas, coste, resumenviviendas, plazo)>
<!ELEMENT codsede (#PCDATA)>
<!ELEMENT nomempleado (#PCDATA)>
<!ELEMENT fechaAlta (#PCDATA)>
<!ELEMENT descripcioncliente (#PCDATA)>
<!ELEMENT codcliente (#PCDATA)>
<!ELEMENT numviviendas (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumenviviendas (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== Jniecor/LMSGI_UD4/Clientes/sede_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sedes SYSTEM "./sede.dtd">
<Sedes>
    <sede>
        <codsede>7869535S</codsede>
        <nomempleado>Antonio</nomempleado>
        <fechaAlta>22/01/2022</fechaAlta>
        <descripcioncliente>solvente</descripcioncliente>
        <clientes>
            <codcliente>JIL-2-5</codcliente>   
            <numviviendas>4</numviviendas>
            <coste>56050€</coste>
            <resumenviviendas>5 habitaciones</resumenviviendas>
            <plazo>2 dias</plazo>
        </clientes>
    </sede>
    <sede>
        <codsede>7854247T</codsede>
        <nomempleado>Jorge</nomempleado>
        <fechaAlta>27/01/2020</fechaAlta>
        <descripcioncliente>insolvente</descripcioncliente>
        <clientes>
            <codcliente>THT-84</codcliente>   
            <numviviendas>8</numviviendas>
            <coste>8000€</coste>
            <resumenviviendas>6 habitaciones</resumenviviendas>
            <plazo>5 dias</plazo>
        </clientes>
    </sede>
</Sedes>
