=== Jniecor/LMSGI_UD4/BDsms/BDsms.dtd
<!ELEMENT BDsms (sms*)>
<!ELEMENT sms (teléfono, fecha, hora, mensaje)>
<!ELEMENT teléfono (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT mensaje (#PCDATA)>

=== Jniecor/LMSGI_UD4/BDsms/BDsms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BDsms SYSTEM "BDsms.dtd">
<BDsms>

    <sms>
        <teléfono>955 55 66 55</teléfono>
        <fecha>1/7/2011</fecha>
        <hora>23:55</hora>
        <mensaje>Juego1:Tetris</mensaje>
    </sms>
    <sms>
        <teléfono>745 15 56 11</teléfono>
        <fecha>22/9/2011</fecha>
        <hora>15:05</hora>
        <mensaje>Juego2:Arkanoid</mensaje>
    </sms>
    <sms>
        <teléfono>842 35 22 00</teléfono>
        <fecha>10/11/2011</fecha>
        <hora>09:22</hora>
        <mensaje>Juego3:Comecocos</mensaje>
    </sms>

</BDsms>
